### ISSUE TITLE
Reset color in prefix

### ISSUE THREAD

**Issue by fam4r** [starcraftman/zsh-git-prompt#16]
Hi,

If user uses colored prompt, prefix string has last used color.

In my case resetting color in following way solved

```bash
ZSH_THEME_GIT_PROMPT_PREFIX="%{$reset_color%}("
```

**Comment by starcraftman** [comment]
Yes I can see that being an issue. I'll just make sure the git prompt is totally isolated by ensuring it begins and ends with a reset flag. That way colouring should always be consistent internally.

**Comment by fam4r** [comment]
Yeah, good.
Is there something I have to do with actual configuration?
Should I remove that option from my config?

**Comment by starcraftman** [comment]
@fam4r You can pull latest and remove the reset from prefix.
