### ISSUE TITLE
[exception] invalid literal for int()

### ISSUE THREAD

**Issue by toshiki-rlearning** [starcraftman/zsh-git-prompt#20]
on gitstatus.py

Exception  in line of 118 on  "parse_ahead_behind()"
```
else:
    behind = int(part.replace('behind ', ''))
```
'part' has 'ahead', 'behind' and 'gone'.

if gone, don't run line of 118.
```
elif 'behind' in part:
    behind = int(part.replace('behind ', ''))
```

**Comment by starcraftman** [comment]
Ah, interesting. Gone means some commits have been simply trimmed from the remote then as opposed to diverging? Simple enough fix, will get on that.

**Comment by starcraftman** [comment]
I don't see gone in the [git status](https://git-scm.com/docs/git-status) documentation, can you tell me simple step to reproduce? Do I just drop a commit in the middle of remotes history?

**Comment by starcraftman** [comment]
Ok, I looked at git source and replicated the issue. Happens when the local branch x is tracking remote/x, then delete remote/x. The upstream itself is 'gone'. Captured output:
```
## w...up/w [gone]
```
